### PR TITLE
Added a new function called gist_map

### PR DESCRIPTION
**Pull request by karthik**
The mapbox map on gists is nice and looks great fullscreen. This function takes an input gist_id object and one geojson file from that set and generates the fullscreen map id.

@sckott, try the example below and let me know what you think before merging.

```r
devtools::install_github("ropensci/gistr@geojson")
library(ecoengine)
library(gistr)
x <- ee_observations(genus = "vulpes")
ee_map(x, dest = "~/Desktop")
gist_id <- gist_create(files = "~/Desktop/temp.geojson", browse = FALSE)
gistr_map(file = "temp.geojson", gist_id)
```

### CODE REVIEW

**Comment by sckott** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by karthik** [comment]
Try again if it fails, fixed a tiny bug in the latest commit.

**Comment by sckott** [comment]
@karthik 

* all fxns are `gist_*`, but this one is `gistr_...`, mind changing to `gist_` instead, or good reason for `gistr`?
* The [footer of the map](http://f.cl.ly/items/1w2m2b3F2a3y1Q2r1X3m/Screen%20Shot%202015-02-15%20at%2012.42.13%20PM.png) doesn't seem to link to the raw file, although it seems to intend to, here `temp.geojson` links to `https://gist.githubusercontent.com//sckott/raw`, which 404s. I imagine it should link to the gist itself?
* Do you mind if we just use base R so we don't need to introduce new pkg deps `stringr` (`strsplit()` instead) and `assertthat` (`stopifnot()`)  - or do you think the fxns from those pkgs are significantly better? These pkgs aren't that heavy, so not a huge deal, but just thought i'd ask.

**Comment by karthik** [comment]
* Fixed fn names
* Footer wasn't designed to link to anything. will look into it.
* Removed stringr but left assert_that since it is considered better practice than stopifnot.

**Comment by karthik** [comment]
* I can't fix the footer because github automatically adds it. I guess they never expected someone would pull such a usecase! :wink:

**Comment by sckott** [comment]
* thx on fxn name
* okay on assertthat
* okay, sounds good on footer

**Comment by sckott** [comment]
@karthik in `#' @param gist_object An object generated by \code{gist_id}` do you mean `gist_create()` ?

**Pull request merged**
