### PR TITLE
warn about staus before checking content type

### PR DESCRIPTION
**Pull request by cpsievert**

### CODE REVIEW

**Comment by cpsievert** [comment]
This should fix #27 (I think)

**Comment by sckott** [comment]
i think the travis fail is fine, i think it shouldn't work on PRs since we use secure env var for testing

**Comment by sckott** [comment]
i think you mean #28 ?

**Comment by sckott** [comment]
i think with #27 we get that error because we have `warn_for_status()`, so a 405 is thrown, but process continues, then the header check is done, and that's a stop function

**Comment by cpsievert** [comment]
Hey Scott :)

When I uploaded large files, I was getting: ` Error: x$headers$`content-type` == "application/json; charset=utf-8" is not TRUE`

This should now at least give an informative warning before that error: `Warning message:
In process(response) : client error: (405) Method Not Allowed`

So, this probably isn't a complete solution, but at least a little closer. Keep up the great work! I may be sending you more PRs in the future :)

**Comment by sckott** [comment]
Right, sounds good. 

Still working on this 405 problem. It doesn't even seem like the right http error code, continue work on this in #27

**Pull request merged**
